language: java

matrix:
  include:
    - jdk: openjdk8
    - jdk: openjdk9
    - jdk: openjdk10
    - jdk: openjdk11
    - jdk: openjdk12
# JDK 13 is not compatible with current Mockito - https://github.com/mockito/mockito/issues/1827
#    - jdk: openjdk13
    - os: osx
      osx_image: xcode9.4
#      env: JAVA_HOME=$(/usr/libexec/java_home)

services:
  - xvfb

before_cache:
  - rm -rf $HOME/.m2/repository/uk/gov/nationalarchives/

cache:
  directories:
    - $HOME/.m2

install:
  - if [ $(mvn -v | grep Java | sed -E 's/.*version: (.*\..*)\..*, vendor:.*/\1/g') = "1.8" ];
    then echo "on Java 8, skip droid-ui module";
    mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V  -pl '!droid-ui';
    else mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V;
    fi;


script:
  - if [ $(mvn -v | grep Java | sed -E 's/.*version: (.*\..*)\..*, vendor:.*/\1/g') = "1.8" ];
    then echo "on Java 8, skip droid-ui module";
    mvn test -B  -pl '!droid-ui';
    else mvn test -B;
    fi;
