//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.22 at 11:40:59 AM GMT 
//


package uk.gov.nationalarchives.droid.report.planets.domain;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.gov.nationalarchives.droid.report.planets.domain package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 * @deprecated PLANETS XML is now generated using XSLT over normal report xml files. 
 */
@XmlRegistry
@Deprecated
public class ObjectFactory {

    private final static QName _FileProfile_QNAME = new QName("http://www.nationalarchives.gov.uk/CollectionProfile", "FileProfile");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.gov.nationalarchives.droid.report.planets.domain
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ByFormatType }
     * 
     */
    public ByFormatType createByFormatType() {
        return new ByFormatType();
    }

    /**
     * Create an instance of {@link PathsProcessedType }
     * 
     */
    public PathsProcessedType createPathsProcessedType() {
        return new PathsProcessedType();
    }

    /**
     * Create an instance of {@link FileProfileType }
     * 
     */
    public FileProfileType createFileProfileType() {
        return new FileProfileType();
    }

    /**
     * Create an instance of {@link FormatItemType }
     * 
     */
    public FormatItemType createFormatItemType() {
        return new FormatItemType();
    }

    /**
     * Create an instance of {@link ByYearType }
     * 
     */
    public ByYearType createByYearType() {
        return new ByYearType();
    }

    /**
     * Create an instance of {@link YearItemType }
     * 
     */
    public YearItemType createYearItemType() {
        return new YearItemType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileProfileType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.nationalarchives.gov.uk/CollectionProfile", name = "FileProfile")
    public JAXBElement<FileProfileType> createFileProfile(FileProfileType value) {
        return new JAXBElement<FileProfileType>(_FileProfile_QNAME, FileProfileType.class, null, value);
    }

}
