//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.22 at 11:40:59 AM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.nationalarchives.gov.uk/CollectionProfile", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package uk.gov.nationalarchives.droid.report.planets.domain;
